#install.packages("tidyverse")
#install.packages("rmarkdown")
#install.packages("httr")
#install.packages("shinydashboard")
#install.packages('leaflet')
#install.packages("vegan")
install.packages("devtools")
devtools::install_github("leffj/mctoolsr")
